[versions]
kotlin = "2.1.0"
kotest = "5.9.1"

[libraries]
testing-kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
